### ISSUE TITLE
Question: does it encode unicode characters?

### ISSUE THREAD

**Issue by krishnaTORQUE** [magiclen/html-escape#4]
Does it encode unicode characters or escape those?

**Comment by magiclen** [comment]
Yes, of course. Did you encounter any problems?

**Comment by krishnaTORQUE** [comment]
Yes
That did not worked, in this snippet.

```rust
use scraper::node::Node;
use scraper::Html;

fn main() {
    let input_text: &str = "<h1>Hello</h1> World 😀 U+1F600";

    println!("{input_text}");

    let frag: Html = Html::parse_fragment(input_text);

    let mut parsed_text: String = String::new();

    for node in frag.tree {
        if let Node::Text(text) = node {
            parsed_text.push_str(&text.text);
        }
    }

    println!("{parsed_text}");
}

```

**Comment by magiclen** [comment]
The `scraper` crate does not depend on my `html-escape` crate. Sorry, I cannot catch it. Could you make it clear?

**Comment by krishnaTORQUE** [comment]
@magiclen Yes
That did not worked, in this snippet.
The smile unicode character does not encoded.

```rust
use html_escape::encode_safe_to_string;

fn main() {
    let input_text: &str = "<h1>Hello</h1> World 😀 U+1F600";
    
    let mut parsed_text: String = String::new();

    encode_safe_to_string(input_text, &mut parsed_text);

    println!("{parsed_text}");
}

```

**Comment by magiclen** [comment]
You should use the `encode_unquoted_attribute*` functions if you want to encode emojis. In your example, the emoji character does not need to be encoded.

**Comment by krishnaTORQUE** [comment]
@magiclen I tried
Its still the same

`encode_unquoted_attribute_to_string(input_text, &mut parsed_text);`

**Comment by magiclen** [comment]
I have reviewed my code. It turns out **only characters which are less than 128 as well as not alphanumeric should be encoded.**

All emojis are greater than 127, so none of them needs to be encoded.

Does this rule cause problems?

**Comment by krishnaTORQUE** [comment]
Causing problem depends on the application.
E.g. if anyone dont want any  of those emoji in their few part of application.
For me I was just testing.

**Comment by magiclen** [comment]
OK, I see. Maybe we could add extra functions like `encode_*_emoji*` to translate emojis to their shortcode and `decode_*_emoji*` functions to translate them back.

**Comment by krishnaTORQUE** [comment]
Yes I think thats a good idea
